### ISSUE TITLE
Add new variable for MultipleChoiceQuestion

### ISSUE THREAD

**Issue by Erik-Iuhas** [Daniel-W-Innes/SYSC4806-Project-Backend#40]
Add a variable to differentiate from different kinds of multiple-choice questions so it could be formatted in the front end, as seen in the image.
![image](https://user-images.githubusercontent.com/71864216/157528582-1c04da34-35c4-4da1-bd6f-d5ad78bab523.png)

**Comment by Daniel-W-Innes** [comment]
![answer](https://user-images.githubusercontent.com/31701786/157533307-c5cd1982-a7ce-419c-9960-ed020dc6aeba.png)

**Comment by Erik-Iuhas** [comment]
Is multiple_choice_question_options a new class or is that just how options are stored?
