### ISSUE TITLE
Create endpoint test cases.

### ISSUE THREAD

**Issue by Erik-Iuhas** [Daniel-W-Innes/SYSC4806-Project-Backend#45]
Write Junit tests which go through the endpoint of the backend.

**Comment by Daniel-W-Innes** [comment]
This ticket requires SpringBootTest; look at Sysc4806ProjectApplicationTests for an elementary example.

**Comment by Erik-Iuhas** [comment]
That test case doesn't pass on my computer, is there a particular way I should set something up to get it to work?

**Comment by Erik-Iuhas** [comment]
> That test case doesn't pass on my computer, is there a particular way I should set something up to get it to work?

Got it working!
