### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by Daniel-W-Innes** [Daniel-W-Innes/SYSC4806-Project-Backend#6]
Setup persistent storage for the backend, my suggestion is to use Postgres. Here is a tutorial from heroku on how to set it up https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku#connecting-to-a-database

**Comment by mariannebrissette3** [comment]
Database created with URL: postgres://esmmgwlselxwyy:64f7833d8ca89858ccd0f16b6d030601118be711b492326d86532b55ecd60127@ec2-50-19-32-96.compute-1.amazonaws.com:5432/d9v74d3e00svh6
